language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew build
  - ./gradlew createDist

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "ttldtor"
  - git config --local user.email "ttldtor@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "./build/distributions/alert_manager-*.spl"
  skip_cleanup: true
  on:
    all_branches: true
